# Generated by Django 5.2.13 on 2026-04-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('text_en', models.TextField(blank=True, default='')),
                ('claim_type', models.CharField(max_length=32)),
                ('source_section_path', models.CharField(blank=True, default='', max_length=512)),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interpret_claims',
            },
        ),
        migrations.CreateModel(
            name='CounterSignal',
            fields=[
                ('signal_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('signal_type', models.CharField(max_length=32)),
                ('evidence_material_id', models.CharField(db_index=True, max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_signals', to='interpret_v2.claim')),
            ],
            options={
                'db_table': 'interpret_counter_signals',
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(db_index=True, max_length=128)),
                ('relation', models.CharField(default='supports', max_length=32)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='interpret_v2.claim')),
            ],
            options={
                'db_table': 'interpret_claim_evidence',
                'unique_together': {('claim', 'material_id')},
            },
        ),
    ]
