# Generated by Django 5.2.13 on 2026-05-04 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('aliases', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='keyword', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'explore_topic',
            },
        ),
        migrations.CreateModel(
            name='ExploreOpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('topic_id', models.CharField(blank=True, max_length=64)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explore_open_question',
            },
        ),
        migrations.CreateModel(
            name='ExploreThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True)),
                ('viewpoint_ids', models.JSONField(default=list)),
                ('paper_keys', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explore_thread',
            },
        ),
        migrations.CreateModel(
            name='ExploreThreadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='explore.explorethread')),
            ],
            options={
                'db_table': 'explore_thread_note',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExploreClaimLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_viewpoint_id', models.CharField(max_length=128)),
                ('dst_viewpoint_id', models.CharField(max_length=128)),
                ('relation', models.CharField(choices=[('agree', 'Agrees'), ('conflict', 'Conflicts'), ('refine', 'Refines')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explore_claim_link',
                'indexes': [models.Index(fields=['user', 'src_viewpoint_id'], name='explore_cla_user_id_90bc91_idx'), models.Index(fields=['user', 'dst_viewpoint_id'], name='explore_cla_user_id_5e07bb_idx')],
                'unique_together': {('user', 'src_viewpoint_id', 'dst_viewpoint_id', 'relation')},
            },
        ),
        migrations.CreateModel(
            name='ExploreActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateField(db_index=True)),
                ('activity', models.FloatField(default=0.0)),
                ('consolidation', models.FloatField(default=0.0)),
                ('viewpoint_total', models.IntegerField(default=0)),
                ('viewpoint_confirmed', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.exploretopic')),
            ],
            options={
                'db_table': 'explore_activity',
                'unique_together': {('snapshot_at', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='ExploreTopicEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('prereq', 'Prerequisite'), ('sub', 'Subtopic'), ('app', 'Application'), ('rel', 'Related')], max_length=16)),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.CharField(default='keyword', max_length=16)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='explore.exploretopic')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='explore.exploretopic')),
            ],
            options={
                'db_table': 'explore_topic_edge',
                'unique_together': {('src', 'dst', 'relation')},
            },
        ),
        migrations.CreateModel(
            name='ExploreVPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewpoint_id', models.CharField(max_length=128)),
                ('from_state', models.CharField(choices=[('unseen', 'Unseen'), ('exposed', 'Exposed'), ('confirmed', 'Confirmed'), ('linked', 'Linked'), ('internalized', 'Internalized')], max_length=16)),
                ('to_state', models.CharField(choices=[('unseen', 'Unseen'), ('exposed', 'Exposed'), ('confirmed', 'Confirmed'), ('linked', 'Linked'), ('internalized', 'Internalized')], max_length=16)),
                ('trigger', models.CharField(choices=[('READ', 'Read'), ('VIEW_EVIDENCE', 'View Evidence'), ('LINK', 'Link'), ('UNLINK', 'Unlink'), ('THREAD_WRITE', 'Thread Write')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explore_vp_event',
                'indexes': [models.Index(fields=['user', 'viewpoint_id'], name='explore_vp__user_id_da0c6f_idx'), models.Index(fields=['created_at'], name='explore_vp__created_c53d9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExploreVPState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewpoint_id', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('unseen', 'Unseen'), ('exposed', 'Exposed'), ('confirmed', 'Confirmed'), ('linked', 'Linked'), ('internalized', 'Internalized')], default='unseen', max_length=16)),
                ('exposed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('link_count', models.IntegerField(default=0)),
                ('internalized_in', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explore_vp_state',
                'indexes': [models.Index(fields=['user', 'state'], name='explore_vp__user_id_d2c163_idx'), models.Index(fields=['last_event_at'], name='explore_vp__last_ev_750500_idx')],
                'unique_together': {('user', 'viewpoint_id')},
            },
        ),
    ]
