# Generated by Django 5.2.13 on 2026-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('seq', models.IntegerField()),
                ('bibkey', models.CharField(blank=True, default='', max_length=128)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extract_citations',
                'indexes': [models.Index(fields=['paper_arxiv_id', 'seq'], name='extract_cit_paper_a_384cd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('seq', models.IntegerField()),
                ('eq_label', models.CharField(blank=True, max_length=64, null=True)),
                ('page', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('latex_or_text', models.TextField(blank=True, default='')),
                ('inline_or_display', models.CharField(default='display', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extract_equations',
                'indexes': [models.Index(fields=['paper_arxiv_id', 'seq'], name='extract_equ_paper_a_c6009a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('seq', models.IntegerField()),
                ('fig_label', models.CharField(blank=True, default='', max_length=64)),
                ('page', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=512)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extract_figures',
                'indexes': [models.Index(fields=['paper_arxiv_id', 'seq'], name='extract_fig_paper_a_1f7076_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('seq', models.IntegerField()),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('char_offset_start', models.IntegerField(default=0)),
                ('char_offset_end', models.IntegerField(default=0)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extract_sections',
                'indexes': [models.Index(fields=['paper_arxiv_id', 'seq'], name='extract_sec_paper_a_a55217_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('seq', models.IntegerField()),
                ('tbl_label', models.CharField(blank=True, default='', max_length=64)),
                ('page', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extract_tables',
                'indexes': [models.Index(fields=['paper_arxiv_id', 'seq'], name='extract_tab_paper_a_8d0655_idx')],
            },
        ),
    ]
