# Generated by Django 5.2.13 on 2026-04-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_pdf_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperBrief',
            fields=[
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='brief', serialize=False, to='papers.paper')),
                ('abstract_zh', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('method_summary_zh', models.TextField(blank=True, default='')),
                ('key_innovation', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('for_you', models.TextField(blank=True, default='')),
                ('tldr_zh', models.TextField(blank=True, default='')),
                ('perspective_used', models.CharField(blank=True, default='', max_length=128)),
                ('model_used', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'papers_brief',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
