# Generated by Django 5.2.13 on 2026-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_backfill_paper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
