# Generated by Django 5.2.13 on 2026-05-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_paper_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbrief',
            name='lang',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
