# Generated by Django 5.2.13 on 2026-04-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenderArtifact',
            fields=[
                ('artifact_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('paper_arxiv_id', models.CharField(db_index=True, max_length=64)),
                ('artifact_type', models.CharField(max_length=32)),
                ('payload_path', models.CharField(max_length=512)),
                ('payload_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'render_artifacts',
            },
        ),
    ]
